package com.utadeo.kalessi.modelos;
// Generated 29-abr-2019 22:04:25 by Hibernate Tools 4.3.1



/**
 * Amantes generated by hbm2java
 */
public class Amantes  implements java.io.Serializable {


     private int idamantes;
     private String grupo;
     private Byte ejecutado;
     private Byte deRealezaDigno;
     private Byte deRealezaNoDigno;

    public Amantes() {
    }

	
    public Amantes(int idamantes) {
        this.idamantes = idamantes;
    }
    public Amantes(int idamantes, String grupo, Byte ejecutado, Byte deRealezaDigno, Byte deRealezaNoDigno) {
       this.idamantes = idamantes;
       this.grupo = grupo;
       this.ejecutado = ejecutado;
       this.deRealezaDigno = deRealezaDigno;
       this.deRealezaNoDigno = deRealezaNoDigno;
    }
   
    public int getIdamantes() {
        return this.idamantes;
    }
    
    public void setIdamantes(int idamantes) {
        this.idamantes = idamantes;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public Byte getEjecutado() {
        return this.ejecutado;
    }
    
    public void setEjecutado(Byte ejecutado) {
        this.ejecutado = ejecutado;
    }
    public Byte getDeRealezaDigno() {
        return this.deRealezaDigno;
    }
    
    public void setDeRealezaDigno(Byte deRealezaDigno) {
        this.deRealezaDigno = deRealezaDigno;
    }
    public Byte getDeRealezaNoDigno() {
        return this.deRealezaNoDigno;
    }
    
    public void setDeRealezaNoDigno(Byte deRealezaNoDigno) {
        this.deRealezaNoDigno = deRealezaNoDigno;
    }




}


