package com.utadeo.kalessi.modelos;
// Generated 29-abr-2019 22:04:25 by Hibernate Tools 4.3.1



/**
 * Dragones generated by hbm2java
 */
public class Dragones  implements java.io.Serializable {


     private int iddragones;
     private Integer edad;
     private String fierza;
     private String color;
     private String nombre;
     private Integer numPersonAsesinadas;
     private String comidaFavorta;

    public Dragones() {
    }

	
    public Dragones(int iddragones) {
        this.iddragones = iddragones;
    }
    public Dragones(int iddragones, Integer edad, String fierza, String color, String nombre, Integer numPersonAsesinadas, String comidaFavorta) {
       this.iddragones = iddragones;
       this.edad = edad;
       this.fierza = fierza;
       this.color = color;
       this.nombre = nombre;
       this.numPersonAsesinadas = numPersonAsesinadas;
       this.comidaFavorta = comidaFavorta;
    }
   
    public int getIddragones() {
        return this.iddragones;
    }
    
    public void setIddragones(int iddragones) {
        this.iddragones = iddragones;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getFierza() {
        return this.fierza;
    }
    
    public void setFierza(String fierza) {
        this.fierza = fierza;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getNumPersonAsesinadas() {
        return this.numPersonAsesinadas;
    }
    
    public void setNumPersonAsesinadas(Integer numPersonAsesinadas) {
        this.numPersonAsesinadas = numPersonAsesinadas;
    }
    public String getComidaFavorta() {
        return this.comidaFavorta;
    }
    
    public void setComidaFavorta(String comidaFavorta) {
        this.comidaFavorta = comidaFavorta;
    }




}


