package com.utadeo.kalessi.modelos;
// Generated 29-abr-2019 22:04:25 by Hibernate Tools 4.3.1



/**
 * Guerreros generated by hbm2java
 */
public class Guerreros  implements java.io.Serializable {


     private int idguerreros;
     private String nombre;
     private String especialidad;
     private String cargo;
     private Integer numPersonasAsesinadas;
     private Byte interesReina;

    public Guerreros() {
    }

	
    public Guerreros(int idguerreros) {
        this.idguerreros = idguerreros;
    }
    public Guerreros(int idguerreros, String nombre, String especialidad, String cargo, Integer numPersonasAsesinadas, Byte interesReina) {
       this.idguerreros = idguerreros;
       this.nombre = nombre;
       this.especialidad = especialidad;
       this.cargo = cargo;
       this.numPersonasAsesinadas = numPersonasAsesinadas;
       this.interesReina = interesReina;
    }
   
    public int getIdguerreros() {
        return this.idguerreros;
    }
    
    public void setIdguerreros(int idguerreros) {
        this.idguerreros = idguerreros;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Integer getNumPersonasAsesinadas() {
        return this.numPersonasAsesinadas;
    }
    
    public void setNumPersonasAsesinadas(Integer numPersonasAsesinadas) {
        this.numPersonasAsesinadas = numPersonasAsesinadas;
    }
    public Byte getInteresReina() {
        return this.interesReina;
    }
    
    public void setInteresReina(Byte interesReina) {
        this.interesReina = interesReina;
    }




}


