package com.utadeo.kalessi.modelos;
// Generated 29-abr-2019 22:04:25 by Hibernate Tools 4.3.1



/**
 * HijosSubditos generated by hbm2java
 */
public class HijosSubditos  implements java.io.Serializable {


     private HijosSubditosId id;
     private Subditos subditos;
     private String nombreHijo;

    public HijosSubditos() {
    }

	
    public HijosSubditos(HijosSubditosId id, Subditos subditos) {
        this.id = id;
        this.subditos = subditos;
    }
    public HijosSubditos(HijosSubditosId id, Subditos subditos, String nombreHijo) {
       this.id = id;
       this.subditos = subditos;
       this.nombreHijo = nombreHijo;
    }
   
    public HijosSubditosId getId() {
        return this.id;
    }
    
    public void setId(HijosSubditosId id) {
        this.id = id;
    }
    public Subditos getSubditos() {
        return this.subditos;
    }
    
    public void setSubditos(Subditos subditos) {
        this.subditos = subditos;
    }
    public String getNombreHijo() {
        return this.nombreHijo;
    }
    
    public void setNombreHijo(String nombreHijo) {
        this.nombreHijo = nombreHijo;
    }




}


