package com.utadeo.kalessi.modelos;
// Generated 29-abr-2019 22:04:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subditos generated by hbm2java
 */
public class Subditos  implements java.io.Serializable {


     private SubditosId id;
     private Territorios territorios;
     private String nombre;
     private String problema;
     private Integer numHijos;
     private Set<HijosSubditos> hijosSubditoses = new HashSet<HijosSubditos>(0);

    public Subditos() {
    }

	
    public Subditos(SubditosId id, Territorios territorios) {
        this.id = id;
        this.territorios = territorios;
    }
    public Subditos(SubditosId id, Territorios territorios, String nombre, String problema, Integer numHijos, Set<HijosSubditos> hijosSubditoses) {
       this.id = id;
       this.territorios = territorios;
       this.nombre = nombre;
       this.problema = problema;
       this.numHijos = numHijos;
       this.hijosSubditoses = hijosSubditoses;
    }
   
    public SubditosId getId() {
        return this.id;
    }
    
    public void setId(SubditosId id) {
        this.id = id;
    }
    public Territorios getTerritorios() {
        return this.territorios;
    }
    
    public void setTerritorios(Territorios territorios) {
        this.territorios = territorios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getProblema() {
        return this.problema;
    }
    
    public void setProblema(String problema) {
        this.problema = problema;
    }
    public Integer getNumHijos() {
        return this.numHijos;
    }
    
    public void setNumHijos(Integer numHijos) {
        this.numHijos = numHijos;
    }
    public Set<HijosSubditos> getHijosSubditoses() {
        return this.hijosSubditoses;
    }
    
    public void setHijosSubditoses(Set<HijosSubditos> hijosSubditoses) {
        this.hijosSubditoses = hijosSubditoses;
    }




}


