package com.utadeo.kalessi.modelos;
// Generated 29-abr-2019 22:04:25 by Hibernate Tools 4.3.1



/**
 * SubditosId generated by hbm2java
 */
public class SubditosId  implements java.io.Serializable {


     private int idsubditos;
     private int territoriosIdterritorios;

    public SubditosId() {
    }

    public SubditosId(int idsubditos, int territoriosIdterritorios) {
       this.idsubditos = idsubditos;
       this.territoriosIdterritorios = territoriosIdterritorios;
    }
   
    public int getIdsubditos() {
        return this.idsubditos;
    }
    
    public void setIdsubditos(int idsubditos) {
        this.idsubditos = idsubditos;
    }
    public int getTerritoriosIdterritorios() {
        return this.territoriosIdterritorios;
    }
    
    public void setTerritoriosIdterritorios(int territoriosIdterritorios) {
        this.territoriosIdterritorios = territoriosIdterritorios;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SubditosId) ) return false;
		 SubditosId castOther = ( SubditosId ) other; 
         
		 return (this.getIdsubditos()==castOther.getIdsubditos())
 && (this.getTerritoriosIdterritorios()==castOther.getTerritoriosIdterritorios());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdsubditos();
         result = 37 * result + this.getTerritoriosIdterritorios();
         return result;
   }   


}


