package com.utadeo.kalessi.modelos;
// Generated 29-abr-2019 22:04:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Territorios generated by hbm2java
 */
public class Territorios  implements java.io.Serializable {


     private int idterritorios;
     private String mapa;
     private String caracteristicas;
     private String nombreRegion;
     private String clima;
     private String productoPrin1;
     private String productoPrin2;
     private String productoPrin3;
     private Set<Subditos> subditoses = new HashSet<Subditos>(0);

    public Territorios() {
    }

	
    public Territorios(int idterritorios) {
        this.idterritorios = idterritorios;
    }
    public Territorios(int idterritorios, String mapa, String caracteristicas, String nombreRegion, String clima, String productoPrin1, String productoPrin2, String productoPrin3, Set<Subditos> subditoses) {
       this.idterritorios = idterritorios;
       this.mapa = mapa;
       this.caracteristicas = caracteristicas;
       this.nombreRegion = nombreRegion;
       this.clima = clima;
       this.productoPrin1 = productoPrin1;
       this.productoPrin2 = productoPrin2;
       this.productoPrin3 = productoPrin3;
       this.subditoses = subditoses;
    }
   
    public int getIdterritorios() {
        return this.idterritorios;
    }
    
    public void setIdterritorios(int idterritorios) {
        this.idterritorios = idterritorios;
    }
    public String getMapa() {
        return this.mapa;
    }
    
    public void setMapa(String mapa) {
        this.mapa = mapa;
    }
    public String getCaracteristicas() {
        return this.caracteristicas;
    }
    
    public void setCaracteristicas(String caracteristicas) {
        this.caracteristicas = caracteristicas;
    }
    public String getNombreRegion() {
        return this.nombreRegion;
    }
    
    public void setNombreRegion(String nombreRegion) {
        this.nombreRegion = nombreRegion;
    }
    public String getClima() {
        return this.clima;
    }
    
    public void setClima(String clima) {
        this.clima = clima;
    }
    public String getProductoPrin1() {
        return this.productoPrin1;
    }
    
    public void setProductoPrin1(String productoPrin1) {
        this.productoPrin1 = productoPrin1;
    }
    public String getProductoPrin2() {
        return this.productoPrin2;
    }
    
    public void setProductoPrin2(String productoPrin2) {
        this.productoPrin2 = productoPrin2;
    }
    public String getProductoPrin3() {
        return this.productoPrin3;
    }
    
    public void setProductoPrin3(String productoPrin3) {
        this.productoPrin3 = productoPrin3;
    }
    public Set<Subditos> getSubditoses() {
        return this.subditoses;
    }
    
    public void setSubditoses(Set<Subditos> subditoses) {
        this.subditoses = subditoses;
    }




}


